name: CI Pipeline for PC Terraform Modules

on:
  push:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && 'main-branch' || 'feature-branches' }}
  cancel-in-progress: true

jobs:
  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

  semantic-release:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: terraform-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.1"

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
