name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  tf:
    runs-on: ubuntu-latest
    environment: prod
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set GIT variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_ENV

      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.2.7

      - name: Iterate through directories and apply Terraform
        run: |
          for dir in */; do
            echo "Processing $dir"
            cd $dir
          terraform init \
            --backend-config="bucket=pc-terraform-modules-tfstate" \
            --backend-config="key=pc-terraform-modules.tfstate"
          terraform plan --out tfplan.out
          terraform apply --auto-approve tfplan.out
          done

  semantic-release:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: tf
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.1"

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
